### ISSUE TITLE
tron mainnet spend too much engergy on fault smart contract transaction

### ISSUE THREAD

**Issue by bigopher** [evolutionlandorg/tron-contracts#50]
{
    "id": "26169b5863045cc2d0baabd32a2ab595eb238ce3859ab0abeff9998f205c0957",
    "fee": 936259920,
    "blockNumber": 5539008,
    "blockTimeStamp": 1546671612000,
    "contractResult": [
        ""
    ],
    "contract_address": "416e0d26adf5323f5b82d5714354dc3c6870adee7c",
    "receipt": {
        "energy_fee": 936259920,
        "origin_energy_usage": 10000000,
        "energy_usage_total": 103625992,
        "net_usage": 476,
        "result": "ILLEGAL_OPERATION"
    },
    "result": "FAILED",
    "resMessage": "496e76616c6964206f7065726174696f6e20636f64653a206f70436f64655b66655d3b"
}

**Comment by HackFisher** [comment]
duplicate with https://github.com/evolutionlandorg/tron-contracts/issues/55
