### ISSUE TITLE
Looks like Tron does not support Proxy?

### ISSUE THREAD

**Issue by hackfisher** [evolutionlandorg/tron-contracts#9]
```
     Error: the object {
  "error": "REVERT opcode executed"
  "output": {
    "blockNumber": 159
    "blockTimeStamp": 1544461047000
    "contractResult": [
      ""
    ]
    "contract_address": "4110ef7929e9ded9fa3f088ad3179d144bb677fb62"
    "fee": 46240
    "id": "346bcef18bd2864831824a6782266567fba2bcb8fce00f7f21370cee2cfc55bf"
    "receipt": {
      "energy_fee": 43100
      "energy_usage_total": 431
      "net_fee": 3140
      "result": "REVERT"
    }
    "resMessage": "524556455254206f70636f6465206578656375746564"
    "result": "FAILED"
  }
  "transaction": {
    "raw_data": {
      "contract": [
        {
          "parameter": {
            "type_url": "type.googleapis.com/protocol.TriggerSmartContract"
            "value": {
              "contract_address": "4110ef7929e9ded9fa3f088ad3179d144bb677fb62"
              "data": "b558a387000000000000000000000000c82449f43925ab729c8ceb4ac8b00aaacd1435d8"
              "owner_address": "41824c483d146a1308d84f69809f6f88e8f5a9538f"
            }
          }
          "type": "TriggerSmartContract"
        }
      ]
      "expiration": 1544461104000
      "fee_limit": 1000000000
      "ref_block_bytes": "009e"
      "ref_block_hash": "1fc12d6168120222"
      "timestamp": 1544461044710
    }
    "signature": [
      "6c693fcc87d1ef872e97bf9c888e59c900c4b529264560cf9e611d95852025608904cac2d98fbbae1c581e1c1445e2223d496ae3933e5f11df34010be96edcff01"
    ]
    "txID": "346bcef18bd2864831824a6782266567fba2bcb8fce00f7f21370cee2cfc55bf"
  }
} was thrown, throw an Error :)
```

**Comment by HackFisher** [comment]
TODO: test with this:

https://github.com/evolutionlandorg/upgradeability-using-eternal-storage/blob/master/contracts/UpgradeabilityStorage.sol

**Comment by HackFisher** [comment]
Proxy is not working due to that TRON TVM does not support fallback function,

and the ABI seems to stored and attached on chain with the contract address, so maybe the TRON node will check the tx contract call if they do not match the ABI,

As a result, TRON do not support Proxy using delegatecall.

**Comment by andyrobert3** [comment]
is this true? 

if so what is the standard for supporting proxy delegate calls on TRON?

**Comment by andyrobert3** [comment]
@hackfisher any news / updates here on how to call the logic address implementation on the proxy contract

**Comment by hujw77** [comment]
Tron now supports proxy delegate calls.

- https://github.com/evolutionlandorg/tron-contracts/blob/migration/contracts/proxy/OwnedUpgradeabilityProxy.sol
- https://github.com/evolutionlandorg/tron-contracts/blob/2505cff33e6dd73a2e55701d01cb77a1f7e02b06/script/landrs_deploy_shasta.js

**Comment by andyrobert3** [comment]
thank you, do you have example for Minimal Proxy pattern or Proxy Factory with CREATE2?

@hujw77, i face difficulties when creating a Minimal Proxy Factory pattern

**Comment by hujw77** [comment]
You could use OpenZepplin libs: https://github.com/OpenZeppelin/openzeppelin-contracts/blob/d39df78f6cf00fee453830ce4500600eabfdbc60/contracts/proxy/Clones.sol#L50

**Comment by andyrobert3** [comment]
@hujw77 i tried but it doesn't work with OpenZeppelin https://github.com/OpenZeppelin/openzeppelin-contracts/blob/d39df78f6cf00fee453830ce4500600eabfdbc60/contracts/proxy/Clones.sol#L50

This is a proxy of a Forwarder
https://shasta.tronscan.io/#/contract/TZ67oJ2t9qdSfYWc5SkkfWTWuQT7rUVVTU/transactions

Calling the `flush` function doesn't flush the funds out 
https://shasta.tronscan.io/#/transaction/9fa6062646a2889108acfb83aa9422ab9cc65a478707678db285090e454bcbd6

Is the bytecode the same? Is there any other proxy pattern / standards you recommend

**Comment by hujw77** [comment]
[Transparent proxy pattern ](https://blog.openzeppelin.com/the-transparent-proxy-pattern) may be a good choice.
